source "https://rubygems.org"

ruby "3.3.11"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "bootsnap", require: false
gem "dotenv-rails", groups: %i[development test]

group :development, :test do
  gem "debug", platforms: %i[mri windows]
end
